project_id = "ctjlgvosazekpxxtxeia"

[functions.provision-twilio-number]
verify_jwt = false

[functions.scrape-website]
verify_jwt = true

[functions.test-chat]
verify_jwt = true

[functions.twilio-status]
verify_jwt = false

[functions.twilio-voice]
verify_jwt = false

[functions.voice-orchestrator]
verify_jwt = false

[functions.structured-llm]
verify_jwt = false